
[build.environment]
  NPM_VERSION = "7.9.0"
  NODE_VERSION = "15.0.1"
  HUGO_VERSION = "0.82.0"

[build]
  publish = "docs/_build/html"
  command = "cd docs && make clean html && cd .."

[context.production]
  publish = "docs/_build/html"
  command = "cd docs && make clean html && cd .."

[context.deploy-preview]
  publish = "docs/_build/html"
  command = "cd docs && make clean html && cd .."

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/docs/fanatical-support-aws/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/docs/fanatical-support-aws/access-and-permissions/user-management-and-perms/*"
  to = "/docs/fanatical-support-aws/user-management-and-perms/:splat"
  status = 404
  force = false

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  prettyURLs = true
  trailingSlash = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"